-- 12A-scalp-v1 shadow/research tables. Additive only: creates scalp12a_*
-- objects and never alters any existing table (11D, HR, pipeline).

CREATE TABLE IF NOT EXISTS scalp12a_shadow_sessions (
    id BIGSERIAL PRIMARY KEY,
    trading_date DATE NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('LIVE_SHADOW', 'REPLAY')),
    strategy_version TEXT NOT NULL,
    config_hash TEXT NOT NULL,
    hr_session_id TEXT,
    status TEXT NOT NULL,
    thresholds JSONB,
    bars_evaluated INTEGER,
    stale_bars INTEGER,
    candidates INTEGER,
    would_trade INTEGER,
    session_reasons JSONB,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes TEXT,
    UNIQUE (trading_date, source, config_hash)
);

CREATE TABLE IF NOT EXISTS scalp12a_candidates (
    id BIGSERIAL PRIMARY KEY,
    trading_date DATE NOT NULL,
    symbol TEXT NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('LIVE_SHADOW', 'REPLAY')),
    strategy_version TEXT NOT NULL,
    config_hash TEXT NOT NULL,
    event_bar_ts TIMESTAMPTZ NOT NULL,
    detected_wall_ts TIMESTAMPTZ,              -- first time the live shadow saw this candidate (never overwritten)
    detection_latency_s DOUBLE PRECISION,       -- detected_wall_ts - end of event bar
    market_mode TEXT NOT NULL,
    is_expiry_day BOOLEAN NOT NULL,
    event_type TEXT NOT NULL,
    event_strength TEXT NOT NULL,
    direction TEXT NOT NULL CHECK (direction IN ('UP', 'DOWN')),
    event_metrics JSONB NOT NULL,
    thresholds JSONB NOT NULL,
    confirmation JSONB NOT NULL,
    context JSONB,
    -- hypothetical option (research only; never an order)
    option_type TEXT,
    strike DOUBLE PRECISION,
    atm_offset INTEGER,
    security_id BIGINT,
    selection JSONB,
    counterfactual_leg_source TEXT,
    -- pre-entry risk
    entry_ref_ask DOUBLE PRECISION,
    stop_price DOUBLE PRECISION,
    target_price DOUBLE PRECISION,
    quantity INTEGER,
    rupee_risk DOUBLE PRECISION,
    underlying_invalidation DOUBLE PRECISION,
    max_hold_seconds INTEGER,
    -- decision
    passed_gates BOOLEAN NOT NULL,
    would_trade BOOLEAN NOT NULL,
    no_trade_reasons TEXT[] NOT NULL,
    satisfied_risk_rules BOOLEAN,
    -- counterfactual outcome (ASK entry, BID path)
    entry_ts TIMESTAMPTZ,
    entry_ask DOUBLE PRECISION,
    entry_spread_pct DOUBLE PRECISION,
    mfe_pct DOUBLE PRECISION,
    mae_pct DOUBLE PRECISION,
    t_mfe_s DOUBLE PRECISION,
    t_mae_s DOUBLE PRECISION,
    horizon_exit_pct JSONB,
    horizon_mfe_pct JSONB,
    horizon_mae_pct JSONB,
    underlying_move DOUBLE PRECISION,
    cf_exit_reason TEXT,
    cf_exit_ts TIMESTAMPTZ,
    cf_exit_bid DOUBLE PRECISION,
    cf_exit_pnl_pct DOUBLE PRECISION,
    cf_hold_seconds DOUBLE PRECISION,
    cf_peak_gain_pct DOUBLE PRECISION,
    cf_giveback_pct DOUBLE PRECISION,
    policy_exit_reason TEXT,
    policy_exit_pnl_pct DOUBLE PRECISION,
    policy_exit_rupees DOUBLE PRECISION,
    outcome_complete BOOLEAN NOT NULL DEFAULT FALSE,
    data_quality TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (trading_date, symbol, source, config_hash, event_bar_ts)
);
-- Opportunity remaining at detection (research measurement; added 2026-09-18, additive)
ALTER TABLE scalp12a_candidates
    ADD COLUMN IF NOT EXISTS event_start_ts TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS event_start_fut DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS detection_bar_end_ts TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS detection_fut DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS detection_option_mid DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS detection_option_ask DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS entry_fut DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS realized_at_detection DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS realized_at_entry DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS fut_mfe_after_detection DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS fut_mae_after_detection DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS t_fut_mfe_after_detection_s DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS t_fut_mae_after_detection_s DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS remaining_after_entry DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS total_event_move DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS remaining_fraction_at_detection DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS remaining_fraction_at_entry DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS option_move_before_entry_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS detection_timing TEXT;
CREATE INDEX IF NOT EXISTS idx_scalp12a_candidates_date ON scalp12a_candidates (trading_date, symbol);
