"""baseline

Revision ID: 9c72bdc253c4
Revises:
Create Date: 2026-07-20 10:23:08.106979

Marks the schema Alembic already found live in the database as the starting
point for future migrations. The 5 tables here (raw_candles,
raw_daily_candles, option_chain_raw, option_chain_summary, levels_snapshots)
are created and owned by the existing ingestion pipeline's
db/setup_db.py + db/schema.sql, NOT by this migration -- autogenerate
correctly produced zero operations because the ORM models were built to
match that live schema exactly (verified: reran --autogenerate after fixing
type/index/server-default drift until it came back empty).

Setup order for a fresh database: (1) `python db/setup_db.py` against the
pipeline's schema.sql, (2) `alembic stamp head` here. This migration should
only ever be reached via `stamp`, never a real `upgrade` -- though since it
has no operations, an accidental `upgrade head` on a fresh DB would simply
do nothing rather than fail or corrupt anything.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c72bdc253c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
